# Generated by Django 3.2.3 on 2021-06-03 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210603_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('discription', models.TextField()),
                ('image', models.ImageField(upload_to='media')),
            ],
        ),
    ]
