# Generated by Django 3.2.3 on 2021-06-03 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_lamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='LampType2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('discription', models.TextField()),
                ('image', models.ImageField(upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='LampType3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('discription', models.TextField()),
                ('image', models.ImageField(upload_to='media')),
            ],
        ),
        migrations.RenameModel(
            old_name='Lamp',
            new_name='LampType1',
        ),
    ]
