# Generated by Django 3.2.3 on 2021-06-06 15:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0003_auto_20210606_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
