# Generated by Django 3.2.3 on 2021-06-06 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_article_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'permissions': (('can_add_article', 'New Can add article'), ('can_manage_article', 'New Can manage article')), 'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
    ]
