# Generated by Django 3.2.3 on 2021-06-08 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_article_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
    ]
